"""
Django settings for ncjm project.

Generated by "django-admin startproject" using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
import json
import logging
import re
from pathlib import Path

import environ
from django.core.exceptions import ImproperlyConfigured
from ncjm.reaction_config import DEFAULT_ALLOWED_REACTIONS

# build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent
print(BASE_DIR)
# get sensitive values from environment conifg (.env)
env = environ.Env()
environ.Env.read_env(BASE_DIR.parent / ".env")

LOG_DIR = "logs"
os.makedirs(LOG_DIR, exist_ok=True)


SECRET_KEY = env("DJANGO_SECRET_KEY")

NCJM_API_ENABLED = env("NCJM_API_ENABLED", default=False)

DEBUG = env("DJANGO_DEBUG", default=False)

GA_ENABLED = env.bool("GA_ENABLED", default=False)
GA_MEASUREMENT_ID = env("GA_MEASUREMENT_ID", default="").strip()

if GA_ENABLED and not re.fullmatch(r"G-[A-Z0-9]+", GA_MEASUREMENT_ID):
    raise ImproperlyConfigured(
        "GA_MEASUREMENT_ID must be a valid GA4 measurement ID when GA_ENABLED is true."
    )

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=[])
CORS_ALLOWED_ORIGINS = env.list("DJANGO_CORS_ORIGIN_WHITELIST", default=[])
CSRF_TRUSTED_ORIGINS = env.list("DJANGO_CSRF_TRUSTED_ORIGINS", default=[])

OAUTH2_PROVIDER = {
    "ACCESS_TOKEN_EXPIRE_SECONDS": 36000,
    "AUTHORIZATION_CODE_EXPIRE_SECONDS": 600,
    "REFRESH_TOKEN_EXPIRE_SECONDS": 86400,
}


RECAPTCHA_PUBLIC_KEY = env("RECAPTCHA_PUBLIC_KEY")
RECAPTCHA_PRIVATE_KEY = env("RECAPTCHA_PRIVATE_KEY")


def _validate_allowed_reactions(value):
    if not isinstance(value, list) or not value:
        raise ValueError("NCJM allowed reactions must be a non-empty list.")

    seen_emojis = set()
    normalized = []

    for entry in value:
        if not isinstance(entry, dict):
            raise ValueError("Each reaction entry must be an object with emoji and label.")

        emoji = str(entry.get("emoji", "")).strip()
        label = str(entry.get("label", "")).strip()

        if not emoji:
            raise ValueError("Each reaction entry must include a non-empty emoji.")
        if not label:
            raise ValueError("Each reaction entry must include a non-empty label.")
        if emoji in seen_emojis:
            raise ValueError("Reaction emojis must be unique.")

        seen_emojis.add(emoji)
        normalized.append({"emoji": emoji, "label": label})

    return normalized


allowed_reactions_raw = env("NCJM_ALLOWED_REACTIONS", default="")
if allowed_reactions_raw:
    NCJM_ALLOWED_REACTIONS = _validate_allowed_reactions(json.loads(allowed_reactions_raw))
else:
    NCJM_ALLOWED_REACTIONS = _validate_allowed_reactions(DEFAULT_ALLOWED_REACTIONS)

NCJM_ALLOWED_REACTIONS_MAP = {
    item["emoji"]: 0 for item in NCJM_ALLOWED_REACTIONS
}

reaction_labels_for_log = ", ".join(
    [f"{item['emoji']}={item['label']}" for item in NCJM_ALLOWED_REACTIONS]
)
logging.getLogger("ncjm.reactions").warning(
    "Loaded %s allowed reactions: %s",
    len(NCJM_ALLOWED_REACTIONS),
    reaction_labels_for_log,
)

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "oauth2_provider",
    "corsheaders",
    "django_extensions",
    "rest_framework",
    "django_recaptcha",


    "ncjm",
    "api",
    "ncjm_site",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
]

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "oauth2_provider.contrib.rest_framework.OAuth2Authentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "120/hour",
        "user": "1000/hour",
    },
    "EXCEPTION_HANDLER": "api.exceptions.api_exception_handler",
}

ROOT_URLCONF = "ncjm.core_urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "ncjm_site", "templates",),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "ncjm_site.context_processors.analytics",
            ],
        },
    },
]

WSGI_APPLICATION = "ncjm.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": env.db(),
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "ncjm_site", "static",)
]
STATIC_ROOT = Path(BASE_DIR) / "public_collected"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
