# Generated by Django 5.1.3 on 2024-11-28 04:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the joke was submitted.')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether the joke has been moved from the approval queue to the main joke list.')),
                ('setup', models.TextField(help_text='The setup of the joke.')),
                ('punchline', models.TextField(help_text='The punchline of the joke.')),
                ('submitter_name', models.CharField(help_text='The name of the person who submitted the joke.', max_length=255)),
                ('slug', models.SlugField(editable=False, help_text='The slugified version of the joke setup.', max_length=255, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='ncjm_joke_slug_ea7807_idx'), models.Index(fields=['id'], name='ncjm_joke_id_acbf8b_idx'), models.Index(fields=['submitter_name'], name='ncjm_joke_submitt_def239_idx')],
                'constraints': [models.UniqueConstraint(fields=('slug',), name='unique_slug')],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='The emoji label for the reaction.', max_length=10)),
                ('text', models.TextField(help_text='The text description of the reaction.')),
                ('joke', models.ForeignKey(help_text='The joke to which this reaction is attached.', on_delete=django.db.models.deletion.CASCADE, to='ncjm.joke')),
            ],
        ),
        migrations.CreateModel(
            name='ReactionTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time when the reaction was made')),
                ('ip_address', models.GenericIPAddressField(help_text='The IP address of the user who reacted')),
                ('user_agent', models.CharField(help_text='The user agent string of the browser used', max_length=255)),
                ('joke', models.ForeignKey(help_text='The joke that received the reaction', on_delete=django.db.models.deletion.CASCADE, to='ncjm.joke')),
                ('reaction', models.ForeignKey(help_text='The reaction given to the joke', on_delete=django.db.models.deletion.CASCADE, to='ncjm.reaction')),
            ],
            options={
                'indexes': [models.Index(fields=['joke', 'reaction', 'ip_address', 'user_agent'], name='ncjm_reacti_joke_id_35c187_idx')],
                'unique_together': {('joke', 'reaction', 'ip_address', 'user_agent')},
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.TextField(help_text='The tag text.', unique=True)),
                ('joke', models.ForeignKey(help_text='The joke to which this tag is attached.', on_delete=django.db.models.deletion.CASCADE, to='ncjm.joke')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tag_text', 'joke'), name='unique_tag_text_joke')],
            },
        ),
    ]
