# Generated by Django 5.1.3 on 2024-11-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncjm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='text',
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_text',
            field=models.CharField(help_text='The tag text.', max_length=100, unique=True),
        ),
    ]
