# Generated by Django 5.1.3 on 2024-11-30 22:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncjm', '0002_remove_reaction_text_alter_tag_tag_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date and time the tag was created.'),
            preserve_default=False,
        ),
    ]
