# Generated by Django 5.1.3 on 2024-12-03 23:21

import ncjm.ncjm.models.CornyJoke
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncjm', '0004_remove_reactiontracker_ncjm_reacti_joke_id_35c187_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='reactions',
            field=models.JSONField(default=dict, help_text='The reactions to the joke stored as totals.'),
        ),
    ]
