# Generated by Django 5.1.3 on 2024-12-04 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncjm', '0005_alter_joke_reactions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
