# Generated by Django 5.1.3 on 2024-12-12 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncjm', '0006_delete_reaction'),
    ]

    operations = [
    ]
