# Generated by Django 5.1.3 on 2024-12-12 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncjm', '0007_auto_20241212_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joke',
            name='ext_id',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='ext_id',
        ),
    ]
