# Generated by Django 5.1.3 on 2025-12-18 05:20

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone

def convert_jokes_to_jokebase(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Joke = apps.get_model("ncjm", "Joke")
    JokeBase = apps.get_model("ncjm", "JokeBase")
    CornyJoke = apps.get_model("ncjm", "CornyJoke")
    ReactionTracker = apps.get_model("ncjm", "ReactionTracker")
    JokeTag = apps.get_model("ncjm", "JokeTag")

    old_ids = list(Joke.objects.using(db_alias).values_list("id", flat=True))

    # Drop rows that would violate FK once we repoint to JokeBase
    ReactionTracker.objects.using(db_alias).exclude(joke_id__in=old_ids).delete()
    JokeTag.objects.using(db_alias).exclude(joke_id__in=old_ids).delete()

    for joke in Joke.objects.using(db_alias).all().iterator():
        created_at = getattr(joke, "created_at", None) or timezone.now()
        is_approved = getattr(joke, "is_approved", False)
        submitter_name = (getattr(joke, "submitter_name", "") or "").strip()
        slug = getattr(joke, "slug", None) or f"joke-{joke.id}"
        is_deleted = getattr(joke, "is_deleted", False)
        reactions = getattr(joke, "reactions", {}) or {}

        # Ensure parent exists (preserve PK). Idempotent if rerun.
        base, _ = JokeBase.objects.using(db_alias).get_or_create(
            id=joke.id,
            defaults={
                "created_at": created_at,
                "is_approved": is_approved,
                "submitter_name": submitter_name,
                "slug": slug,
                "is_deleted": is_deleted,
                "reactions": reactions,
            },
        )

        # Ensure child exists (link to the saved parent instance).
        if not CornyJoke.objects.using(db_alias).filter(pk=base.pk).exists():
            CornyJoke.objects.using(db_alias).create(
                jokebase_ptr=base,
                setup=getattr(joke, "setup", "") or "",
                punchline=getattr(joke, "punchline", "") or "",
            )

        
class Migration(migrations.Migration):
    dependencies = [
        ('ncjm', '0008_remove_joke_ext_id_remove_tag_ext_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JokeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the joke was submitted.')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether the joke has been moved from the approval queue to the main joke list.')),
                ('submitter_name', models.CharField(help_text='The name of the person who submitted the joke.', max_length=255)),
                ('slug', models.SlugField(editable=False, help_text='The slugified version of the joke setup.', max_length=255, unique=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether the joke has been deleted.')),
                ('reactions', models.JSONField(default=dict, help_text='The reactions to the joke stored as totals.')),
                ('tags', models.ManyToManyField(help_text='The tags associated with the joke.', related_name='jokes', related_query_name='joke', through='ncjm.JokeTag', to='ncjm.tag')),
            ],
        ),
        migrations.RemoveField(
            model_name='joke',
            name='tags',
        ),
        migrations.CreateModel(
            name='CornyJoke',
            fields=[
                ('jokebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ncjm.jokebase')),
                ('setup', models.TextField(help_text='The setup of the joke.')),
                ('punchline', models.TextField(help_text='The punchline of the joke.')),
            ],
            bases=('ncjm.jokebase',),
        ),
        migrations.CreateModel(
            name='LongJoke',
            fields=[
                ('jokebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ncjm.jokebase')),
                ('title', models.TextField(help_text='The title of the joke.')),
                ('transcript', models.TextField(help_text='The text of the joke.')),
                ('notes', models.TextField(blank=True, help_text='Any notes about the joke.', null=True)),
                ('hidden_notes', models.TextField(blank=True, help_text='Any notes about the joke that should not be immediately visible', null=True)),
                ('media_url', models.URLField(blank=True, help_text='A URL to an audio or video recording of the joke.', null=True)),
            ],
            bases=('ncjm.jokebase',),
        ),

        migrations.RunPython(convert_jokes_to_jokebase, reverse_code=migrations.RunPython.noop),

        migrations.AlterField(
            model_name='joketag',
            name='joke',
            field=models.ForeignKey(help_text='The joke that was tagged', on_delete=django.db.models.deletion.CASCADE, to='ncjm.jokebase'),
        ),
        migrations.AlterField(
            model_name='reactiontracker',
            name='joke',
            field=models.ForeignKey(help_text='The joke that received the reaction', on_delete=django.db.models.deletion.CASCADE, to='ncjm.jokebase'),
        ),
        migrations.AddIndex(
            model_name='jokebase',
            index=models.Index(fields=['slug'], name='ncjm_jokeba_slug_65d09f_idx'),
        ),
        migrations.AddIndex(
            model_name='jokebase',
            index=models.Index(fields=['id'], name='ncjm_jokeba_id_059cc0_idx'),
        ),
        migrations.AddIndex(
            model_name='jokebase',
            index=models.Index(fields=['submitter_name'], name='ncjm_jokeba_submitt_b5d430_idx'),
        ),
        migrations.AddConstraint(
            model_name='jokebase',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_slug'),
        ),
        migrations.DeleteModel(
            name='Joke',
        ),
    ]
