services:
  web:
    build:
      context: ..
      dockerfile: ./.docker/Dockerfile.ncjm
    container_name: ncjm_app
    env_file:
      - ../.env
    volumes:
      - ../ncjm/db.sqlite3:/home/ncjm/app/db.sqlite3
      - ../public_collected/:/home/ncjm/app/public_collected
    working_dir: /home/ncjm/app
    command: ["gunicorn", "ncjm.wsgi:application", "--bind", "0.0.0.0:8000"]
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    container_name: ncjm_nginx
    env_file:
      - ../.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../public_collected/:/home/ncjm/public_collected
      - ../.nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - certbot-webroot:/var/www/certbot
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    container_name: ncjm_certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/log/letsencrypt:/var/log/letsencrypt
<<<<<<< HEAD
      - certbot-webroot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;'"

volumes:
  certbot-webroot:
=======
    entrypoint: >
      /bin/sh -c '
      trap exit TERM;
      while :; do
        certbot renew --deploy-hook "docker kill -s HUP ncjm_nginx";
        sleep 12h & wait $${!};
      done;
      '
>>>>>>> d6d7c5d (fix: update nginx image from 1.19.0 to current stable)
