services:
  web:
    build:
      context: ..
      dockerfile: ./.docker/Dockerfile.ncjm
    container_name: ncjm_app
    env_file:
      - ../.env
    volumes:
      - ../ncjm/db.sqlite3:/home/ncjm/app/db.sqlite3
      - ../public_collected/:/home/ncjm/app/public_collected
    working_dir: /home/ncjm/app
    command: ["gunicorn", "ncjm.wsgi:application", "--bind", "0.0.0.0:8000"]
    ports:
      - "8000:8000"

  nginx:
    image: nginx:1.19.0-alpine
    container_name: ncjm_nginx
    env_file:
      - ../.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../public_collected/:/home/ncjm/public_collected
      - ../.nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    container_name: ncjm_certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /var/log/letsencrypt:/var/log/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"